version: '3.5'
networks:
  dm_pod:
    driver: bridge
services:
  producer:
    #image: producer:deney5
    image: producer:dep-1
    container_name: producer
    environment:
      - SERVER_PORT=8081
      #- USER_NAME=user
      #- USER_PASSWORD=user
      - HOST=rabbitmq
      - PORT=5672
      - QUEUE_NAME=myqueue
      - EXCHANGE_NAME=myTopicExchange
      - ROUTING_KEY=myRoutingKey.#
      - VAULT_NAME=vaultdemo
      - VAULT_TOKEN=hvs.qyegCIkJFrZLnP8lQn5e1QRD
      - VAULT_HOST=localhost
      - VAULT_PORT=8200
    ports:
      - 8081:8081
#    volumes:
#      - ./config:/conf
#    depends_on:
#      - rabbitmq
    networks:
      - dm_pod
  consumer:
    image: consumer:1
    container_name: consumer
    ports:
      - 8080:8080
    volumes:
      - ./config:/conf
    depends_on:
      - rabbitmq
      - producer
    networks:
      - dm_pod
  rabbitmq:
    image: nexus.dev.visualize.softtech.com.tr/repository/dap/rabbitmq:1
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    volumes:
      - ./rabbit_data:/bitnami/rabbitmq/mnesia
    networks:
      - dm_pod
